// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: app/order/cmd/rpc/pb/order.proto

package order_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderResponse_PhoneType int32

const (
	OrderResponse_MOBILE OrderResponse_PhoneType = 0
	OrderResponse_HOME   OrderResponse_PhoneType = 1
	OrderResponse_WORK   OrderResponse_PhoneType = 2
)

// Enum value maps for OrderResponse_PhoneType.
var (
	OrderResponse_PhoneType_name = map[int32]string{
		0: "MOBILE",
		1: "HOME",
		2: "WORK",
	}
	OrderResponse_PhoneType_value = map[string]int32{
		"MOBILE": 0,
		"HOME":   1,
		"WORK":   2,
	}
)

func (x OrderResponse_PhoneType) Enum() *OrderResponse_PhoneType {
	p := new(OrderResponse_PhoneType)
	*p = x
	return p
}

func (x OrderResponse_PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderResponse_PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_order_cmd_rpc_pb_order_proto_enumTypes[0].Descriptor()
}

func (OrderResponse_PhoneType) Type() protoreflect.EnumType {
	return &file_app_order_cmd_rpc_pb_order_proto_enumTypes[0]
}

func (x OrderResponse_PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderResponse_PhoneType.Descriptor instead.
func (OrderResponse_PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{1, 0}
}

// ==========================
type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //传入person id
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id     int32                        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email  string                       `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones []*OrderResponse_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OrderResponse) GetPhones() []*OrderResponse_PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

type OrderResponse_PhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string                  `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type   OrderResponse_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=app.order.cmd.rpc.pb.OrderResponse_PhoneType" json:"type,omitempty"`
}

func (x *OrderResponse_PhoneNumber) Reset() {
	*x = OrderResponse_PhoneNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse_PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse_PhoneNumber) ProtoMessage() {}

func (x *OrderResponse_PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse_PhoneNumber.ProtoReflect.Descriptor instead.
func (*OrderResponse_PhoneNumber) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OrderResponse_PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderResponse_PhoneNumber) GetType() OrderResponse_PhoneType {
	if x != nil {
		return x.Type
	}
	return OrderResponse_MOBILE
}

var File_app_order_cmd_rpc_pb_order_proto protoreflect.FileDescriptor

var file_app_order_cmd_rpc_pb_order_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x70, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x61, 0x70, 0x70, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x63, 0x6d,
	0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x62, 0x22, 0x1e, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa9, 0x02, 0x0a, 0x0d, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x47, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x1a, 0x68, 0x0a,
	0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x63,
	0x6d, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x4f,
	0x52, 0x4b, 0x10, 0x02, 0x32, 0x66, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x63, 0x6d,
	0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x2f, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_order_cmd_rpc_pb_order_proto_rawDescOnce sync.Once
	file_app_order_cmd_rpc_pb_order_proto_rawDescData = file_app_order_cmd_rpc_pb_order_proto_rawDesc
)

func file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP() []byte {
	file_app_order_cmd_rpc_pb_order_proto_rawDescOnce.Do(func() {
		file_app_order_cmd_rpc_pb_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_order_cmd_rpc_pb_order_proto_rawDescData)
	})
	return file_app_order_cmd_rpc_pb_order_proto_rawDescData
}

var file_app_order_cmd_rpc_pb_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_order_cmd_rpc_pb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_order_cmd_rpc_pb_order_proto_goTypes = []interface{}{
	(OrderResponse_PhoneType)(0),      // 0: app.order.cmd.rpc.pb.OrderResponse.PhoneType
	(*OrderRequest)(nil),              // 1: app.order.cmd.rpc.pb.OrderRequest
	(*OrderResponse)(nil),             // 2: app.order.cmd.rpc.pb.OrderResponse
	(*OrderResponse_PhoneNumber)(nil), // 3: app.order.cmd.rpc.pb.OrderResponse.PhoneNumber
}
var file_app_order_cmd_rpc_pb_order_proto_depIdxs = []int32{
	3, // 0: app.order.cmd.rpc.pb.OrderResponse.phones:type_name -> app.order.cmd.rpc.pb.OrderResponse.PhoneNumber
	0, // 1: app.order.cmd.rpc.pb.OrderResponse.PhoneNumber.type:type_name -> app.order.cmd.rpc.pb.OrderResponse.PhoneType
	1, // 2: app.order.cmd.rpc.pb.OrderService.OrderInfo:input_type -> app.order.cmd.rpc.pb.OrderRequest
	2, // 3: app.order.cmd.rpc.pb.OrderService.OrderInfo:output_type -> app.order.cmd.rpc.pb.OrderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_order_cmd_rpc_pb_order_proto_init() }
func file_app_order_cmd_rpc_pb_order_proto_init() {
	if File_app_order_cmd_rpc_pb_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_order_cmd_rpc_pb_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_order_cmd_rpc_pb_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_order_cmd_rpc_pb_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse_PhoneNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_order_cmd_rpc_pb_order_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_order_cmd_rpc_pb_order_proto_goTypes,
		DependencyIndexes: file_app_order_cmd_rpc_pb_order_proto_depIdxs,
		EnumInfos:         file_app_order_cmd_rpc_pb_order_proto_enumTypes,
		MessageInfos:      file_app_order_cmd_rpc_pb_order_proto_msgTypes,
	}.Build()
	File_app_order_cmd_rpc_pb_order_proto = out.File
	file_app_order_cmd_rpc_pb_order_proto_rawDesc = nil
	file_app_order_cmd_rpc_pb_order_proto_goTypes = nil
	file_app_order_cmd_rpc_pb_order_proto_depIdxs = nil
}
