definitions:
  main.GreeterResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/greeter:
    get:
      operationId: "1"
      parameters:
      - description: Input name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GreeterResponse'
      summary: Greeter service
swagger: "2.0"
